name: Test Impact Analysis
 
on:
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: windows-latest
    environment: testing
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Checkout TIA
      uses: actions/checkout@v3
      with:
        repository: jc121f1/TestImpactAnalysis
        token: ${{ secrets.GH_PT }}
        path: TIA
    - name: Remove File
      uses: JesseTG/rm@v1.0.0
      with:
        path: TIA/tests
    - name: Download testimpact artifacts
      uses: actions/cache/restore@v3
      with:
        key: testimpactfiles
        path: coverage_dir
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r TIA/requirements.txt
    - name: Select Tests and Execute 
      run: |
        python TIA/test_impact_launcher.py --init-commit ${{ github.event.pull_request.base.sha }} --final-commit ${{ github.event.pull_request.head.sha }} --changelist-generator git --test-architecture pytest
    - name: Save testimpact artifacts
      uses: actions/cache/save@v3
      with:
        key: testimpactfiles
        path: coverage_dir